services:
  php:
    build:
      context: .
      dockerfile: ./docker/php.cnf/Dockerfile
    image: projectrestaurant
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    container_name: php83
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - ../mysql/:/home/
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dbRestaurant
    container_name: mysql
volumes:
  mysql-volume:
